IGI/LR5/LabRab5_IGI/LabRab5_IGI/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path
from django.urls import include

from onlineshop.views import RegisterView

urlpatterns = [
    path('admin/', admin.site.urls),
]
urlpatterns += [
    path('onlineshop/', include('onlineshop.urls')),
]
from django.views.generic import RedirectView

urlpatterns += [
    path('', RedirectView.as_view(url='/onlineshop/', permanent=True)),
]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += [
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('accounts/', include('django.contrib.auth.urls')),
]
urlpatterns += [
    path('sign-up', RegisterView.as_view(), name='sign-up'),
]
from django.conf import settings
from django.conf.urls.static import static

# ... your existing urlpatterns ...

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

IGI/LR5/LabRab5_IGI/onlineshop/urls.py
from django.urls import path
from . import views
from django.urls import re_path

from .views import AllClientsForEmployeeView, LogoutView

# urlpatterns = [
#     path('', views.index, name='index'),
#     path('products/', views.ProductListView.as_view(), name='products'),
#
#
#     path('product/<int:pk>', views.ProductDetailView.as_view(), name='product-detail'),
# ]

urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^products/$', views.ProductListView.as_view(), name='products'),
    re_path(r'^product/(?P<pk>\d+)$', views.ProductDetailView.as_view(), name='product-detail'),
    re_path(r'^manufacturers/$', views.ManufacturerListView.as_view(), name='manufacturers'),
    re_path(r'^manufacturers/(?P<pk>\d+)$', views.ManufacturerDetailView.as_view(), name='manufacturer-detail'),
]
urlpatterns += [
    re_path(r'^myproducts/$', views.OrderedProductsByUserListView.as_view(), name='my-ordered'),
]
urlpatterns += [
    re_path(r'^all-orders/$', views.AllOrdersForEmployeeView.as_view(), name='all-orders'),
]
urlpatterns += [
    re_path(r'^order/(?P<pk>[-\w]+)/change-status/$', views.change_status_employee, name='change-status-employee'),

]
urlpatterns += [
    re_path(r'^orders/$', views.OrdersByUserListView.as_view(), name='my-orders'),
]
urlpatterns += [
    re_path(r'^orders/(?P<order_id>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/$', views.OrderedProductsByUserListView.as_view(), name='order-detail'),
]
urlpatterns += [
    # ... your other url patterns here ...

    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
]
urlpatterns += [
    re_path(r'^cart/$', views.CartView.as_view(), name='cart'),
]
urlpatterns += [
    path('create-order/', views.create_order, name='create-order'),
]

urlpatterns += [
    re_path(r'^increase-quantity/(?P<product_instance_id>[0-9a-f-]+)/$', views.increase_quantity,
            name='increase-quantity'),
    re_path(r'^decrease-quantity/(?P<product_instance_id>[0-9a-f-]+)/$', views.decrease_quantity,
            name='decrease-quantity'),
    re_path(r'^remove-from-cart/(?P<product_instance_id>[0-9a-f-]+)/$', views.remove_from_cart,
            name='remove-from-cart'),
]

urlpatterns += [
    path('onlineshop/cart/apply-promo-code/', views.apply_promo_code, name='apply-promo-code'),
]
urlpatterns += [
    path('promo-codes/', views.PromoCodeListView.as_view(), name='promo-codes'),
]
urlpatterns += [
    path('pickup-locations/', views.PickupLocationListView.as_view(), name='pickup-locations'),
]
urlpatterns += [
    path('clients/', views.client_list, name='clients'),
]

urlpatterns += [
    path('clients/all/', views.AllClientsForEmployeeView.as_view(), name='all-clients'),
]
from .views import EmployeeListView

urlpatterns += [
    path('contacts/', EmployeeListView.as_view(), name='contacts'),
]
from .views import ReviewListView, ReviewCreateView

urlpatterns += [
    path('reviews/', ReviewListView.as_view(), name='reviews'),
    path('reviews/add/', ReviewCreateView.as_view(), name='add-review'),
]
from .views import employee_stats

urlpatterns += [
    path('employee-stats/', employee_stats, name='employee-stats'),
]
urlpatterns += [
    path('logout/', LogoutView.as_view(), name='logout'),
]
urlpatterns += [
    path('privacy-policy/', views.privacy_policy, name='privacy_policy'),
]
urlpatterns += [
    path('news/', views.news, name='news'),
    path('news/<int:article_id>/', views.article_detail, name='article_detail'),
]
urlpatterns += [
    path('about/', views.about, name='about'),
]
urlpatterns += [
    path('faq/', views.faq, name='faq'),
]
urlpatterns += [
    path('jobs/', views.jobs, name='jobs'),
]
from django.urls import path
from . import views

urlpatterns += [
    path('employees/', views.employee_table, name='employee_table'),
]

urlpatterns += [
    path('add_employee/', views.add_employee, name='add_employee'),
    # Другие маршруты
]

IGI/LR5/LabRab5_IGI/onlineshop/models.py
import uuid

from django.db import models
from django.db.models.signals import m2m_changed
from django.dispatch import receiver
from django.urls import reverse

import sys
from django.contrib.auth.models import User, Group

sys.path.append('D:\\3 SEM\\253503_TIMOSHEVICH_25\\IGI\\LR5\\LabRab5_IGI\\.venv\\Lib\\site-packages')

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Employee(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, default=3)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    position = models.CharField(max_length=100)
    photo = models.ImageField(upload_to='', null=True, blank=True)
    job_description = models.TextField(default='')
    phone = models.CharField(max_length=20, default='')
    email = models.EmailField(default='default@email.com')

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        group = Group.objects.get(name='Employees')
        self.user.groups.add(group)


class Client(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, default=2)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    phone_number = models.CharField(max_length=20, default='', blank=True)

    def __str__(self):
        return f"{self.user.username}"

    class Meta:
        ordering = ["last_name", "first_name"]

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        group = Group.objects.get(name='Shop Members')
        self.user.groups.add(group)


class ProductType(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Manufacturer(models.Model):
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=200)
    phone = models.CharField(max_length=20)
    logo = models.ImageField(upload_to='images/', null=True)
    website = models.URLField(null=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('manufacturer-detail', args=[str(self.id)])


class UnitOfMeasure(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    product_type = models.ForeignKey(ProductType, on_delete=models.CASCADE)
    manufacturer = models.ForeignKey("Manufacturer", on_delete=models.CASCADE, null=True)
    unit_of_measure = models.ForeignKey(UnitOfMeasure, on_delete=models.SET_NULL, null=True)
    image = models.ImageField(upload_to='product_images/', blank=True, null=True)
    # image = models.ImageField(upload_to='products/', null=True, blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product-detail', args=[str(self.id)])


class ProductInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text="Unique ID for this particular product across whole shop")
    product = models.ForeignKey('Product', on_delete=models.SET_NULL, null=True)
    # order = models.ForeignKey(Order, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    customer = models.ForeignKey(Client, on_delete=models.SET_NULL, null=True, blank=True)

    @property
    def total_price(self):
        return self.product.price * self.quantity

    class Meta:
        permissions = (("can_mark_issued", "Set product as issued"),)

    def __str__(self):
        """
        String for representing the Model object
        """
        return '%s (%s)' % (self.id, self.product.name)


class PickupLocation(models.Model):
    name = models.CharField(max_length=200)
    address = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class PromoCode(models.Model):
    code = models.CharField(max_length=10)
    discount = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.code


class Order(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text="Unique ID for this particular product across whole shop")
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    products = models.ManyToManyField(ProductInstance)
    order_date = models.DateTimeField(auto_now_add=True)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)
    promo_code = models.ForeignKey(PromoCode, on_delete=models.SET_NULL, null=True, blank=True)  # new field
    pickup_location = models.ForeignKey(PickupLocation, on_delete=models.SET_NULL, null=True, blank=True)

    LOAN_STATUS = (
        ('p', 'Processing'),
        ('s', 'Shipped'),
        ('d', 'Delivered'),
        ('i', 'Issued'),
    )

    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='p',
                              help_text='Status of the order')

    def save(self, *args, **kwargs):
        self.total_price = sum(
            product_instance.product.price * product_instance.quantity for product_instance in self.products.all())
        if self.promo_code:
            self.total_price *= (1 - self.promo_code.discount / 100)
        super().save(*args, **kwargs)

    def update_total_price(self):
        total_price = sum(
            product_instance.product.price * product_instance.quantity for product_instance in self.products.all())
        if self.promo_code:
            total_price *= (1 - self.promo_code.discount / 100)
        self.total_price = total_price
        self.save()

    def __str__(self):
        return f"Order {self.id} by {self.client}"


@receiver(m2m_changed, sender=Order.products.through)
def update_total_price(sender, instance, action, **kwargs):
    if action == "post_add" or action == "post_remove":
        instance.total_price = sum(
            product_instance.product.price * product_instance.quantity for product_instance in instance.products.all())
        instance.save()


class Cart(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    products = models.ManyToManyField(ProductInstance)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)
    promo_code = models.ForeignKey(PromoCode, on_delete=models.SET_NULL, null=True, blank=True)  # new field

    def __str__(self):
        return f"Cart for {self.client}"

    def update_total_price(self):
        total_price = sum(
            product_instance.product.price * product_instance.quantity for product_instance in self.products.all())
        if self.promo_code:
            total_price *= (1 - self.promo_code.discount / 100)
        self.total_price = total_price
        self.save()


class Review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rating = models.IntegerField()
    text = models.TextField()
    date = models.DateTimeField(auto_now_add=True)


from django.utils import timezone


class Article(models.Model):
    title = models.CharField(max_length=200)
    summary = models.CharField(max_length=200)
    image = models.ImageField(upload_to='articles/')
    content = models.TextField()
    date_added = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title


class CompanyInfo(models.Model):
    text = models.TextField()
    video = models.FileField(upload_to='company_info/')
    logo = models.ImageField(upload_to='company_info/')
    banner1 = models.ImageField(upload_to='company_info/', null=True, blank=True)
    banner2 = models.ImageField(upload_to='company_info/', null=True, blank=True)
    banner3 = models.ImageField(upload_to='company_info/', null=True, blank=True)  # Новое поле
    privacy_policy = models.FileField(upload_to='employee_photos/policies/', null=True, blank=True)

    audio = models.FileField(upload_to='company_info/', null=True, blank=True)

    history = models.TextField()
    details = models.TextField()

    def __str__(self):
        return "Company Information"


class FAQ(models.Model):
    question = models.TextField()
    answer = models.TextField()
    date_added = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.question


class Job(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()

    def __str__(self):
        return self.title

IGI/LR5/LabRab5_IGI/onlineshop/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
import datetime  # for checking renewal date range.

from .models import Order, PickupLocation


class OrderStatusForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['status']


from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from datetime import date, timedelta
from django.core.validators import RegexValidator


class RegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)
    date_of_birth = forms.DateField(
        help_text="Required. Format: DD.MM.YYYY",
        input_formats=['%d.%m.%Y']
    )
    phone_number = forms.CharField(
        validators=[
            RegexValidator(
                regex=r'^\+375 \((29|33|44|25)\) \d{3}-\d{2}-\d{2}$',
                message="Phone number must be entered in the format: '+375 (29) XXX-XX-XX'. Up to 15 digits allowed."
            )
        ]
    )

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ["username", "email", "password1", "password2", "date_of_birth", "phone_number"]

    def clean_date_of_birth(self):
        dob = self.cleaned_data.get('date_of_birth')
        today = date.today()
        if (dob.year + 18, dob.month, dob.day) > (today.year, today.month, today.day):
            raise forms.ValidationError('You must be at least 18 years old to register.')
        return dob


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['pickup_location']
        widgets = {
            'pickup_location': forms.Select(attrs={'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        self.fields['pickup_location'].empty_label = None


from django import forms
from .models import Review


class ReviewForm(forms.ModelForm):
    RATING_CHOICES = [(i, str(i)) for i in range(1, 6)]

    rating = forms.ChoiceField(choices=RATING_CHOICES, widget=forms.Select(), required=True, initial=5)

    class Meta:
        model = Review
        fields = ['rating', 'text']

IGI/LR5/LabRab5_IGI/onlineshop/templates/onlineshop/about.html
{% extends "base_generic.html" %}
{% load static %}
{% block content %}
    <h1 class="itim-regular">About company</h1>
   <img src="{{ info.logo.url }}" alt="Company Logo" height=200px width=200px class="logo-transform">
   <p class="text-wrap">{{ info.text }}</p>

    <div class="products-animation-scroll">
        <div class="product-animation-scroll" id="product1-scroll">🍎</div>
        <div class="product-animation-scroll" id="product2-scroll">🥕</div>
        <div class="product-animation-scroll" id="product3-scroll">🍋</div>
    </div>
    <div class="cart-animation-scroll" id="cart-animation-scroll">🛒</div>

    <video class="styled-video" controls autoplay muted>
        <source src="{{ info.video.url }}" type="video/mp4">
    </video>
    <br>
    <audio class="styled-audio" controls>
        <source src="{{ info.audio.url }}" type="audio/mpeg">
        Your browser does not support the audio element.
    </audio>
    <h2 class="itim-regular">History</h2>
    <ul class="history-list">
        <li>2020: Company founded</li>
        <li>2021: Launched first product line</li>
        <li>2022: Expanded to international markets</li>
        <li>2023: Reached 1 million customers</li>
        <li>2024: Introduced new innovative technologies</li>
    </ul>
    <h2 class="itim-regular">Banking Details</h2>
    <p class="banking-details">{{ info.details }}</p>
    <h2 class="itim-regular">Our certificate</h2>
    <div class="certificate-container" id="about_company">
    <h1 class="h1-certificate">Свидетельство о качестве продукции</h1>

    <div class="certificate-content">
        <p>Настоящим удостоверяется, что <strong class="certificate">Онлайн-магазин "FreshMarket"</strong>
            успешно прошел все необходимые проверки и обладает
            всеми необходимыми ресурсами, квалифицированным персоналом и оборудованием для обеспечения
            высокого качества продуктов на территории Республики Беларусь.</p>

        <p>Компания "FreshMarket" осуществляет следующие виды услуг:</p>
        <ul class="certificate-list">
            <li>Быстрая доставка свежих продуктов на дом;</li>
            <li>Широкий ассортимент органических и фермерских продуктов;</li>
            <li>Удобный онлайн-заказ и оплата;</li>
            <li>Гарантия качества и свежести продуктов;</li>
            <li>Профессиональная консультация по выбору продуктов.</li>
        </ul>

        <p>Компания имеет лицензию №987654321 от 16 октября 2024 года и выполняет работы в соответствии с
            действующими стандартами и нормами охраны труда и техники безопасности.</p>
        <p>Срок действия данного свидетельства: с 16 октября 2024 года по 01 января 2025 года.</p>
    </div>
    <div class="certificate-sign">
        <img src="{% static 'images/podpis.png' %}"
             alt="Company Seal">
    </div>
     <div class="certificate-pechat">
        <img src="{% static 'images/sign.png' %}" alt="Company Seal">
    </div>

    <div class="certificate-signatures">
        <div class="certificate-signature-line">
            <div>
                ___________________________<br>
                <em>Генеральный директор</em><br>
                Иванов И.И.
            </div>
        </div>
    </div>

    <footer class="certificate">
        <p> 2024 - Ассоциация контроля нормы торговли.</p>
    </footer>
</div>
<div class="contact-section">
    <p class="itim-regular">Contact with us:</p>
    <div class="button-container">
        <button class="btn-emerald" onclick="location.href='mailto:milana03tima@gmail.com?subject=Question'">Email us</button>
        <button class="btn-emerald" onclick="location.href='tel:+375292568820'">Call us</button>
    </div>
</div>
    {% block scripts %}
<script src="{% static 'js/animation.js' %}"></script>
{% endblock %}
{% endblock %}

IGI/LR5/LabRab5_IGI/onlineshop/templates/onlineshop/add_employee.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Employee List</h1>
<button id="toggleForm">Add Employee</button>

<div id="employeeForm" style="display: none; margin-top: 20px; border: 1px solid #ccc; padding: 15px;">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div>
            <label>First Name:</label>
            <input type="text" name="first_name" required>
        </div>
        <div>
            <label>Last Name:</label>
            <input type="text" name="last_name" required>
        </div>
        <div>
            <label>Position:</label>
            <input type="text" name="position" required>
        </div>
        <div>
            <label>Photo:</label>
            <input type="file" name="photo">
        </div>
        <div>
            <label>Job Description:</label>
            <textarea name="job_description"></textarea>
        </div>
        <div>
            <label>Phone:</label>
            <input type="text" name="phone" required>
            {% if error_message == 'Invalid phone number' %}
            <span class="error">Invalid phone number</span>
            {% endif %}
        </div>
        <div>
            <label>Email:</label>
            <input type="email" name="email" required>
        </div>
        <div>
            <label>Username:</label>
            <input type="text" name="username" required>
        </div>
        <div>
            <label>Password:</label>
            <input type="password" name="password" required>
        </div>
        <div>
            <label>Confirm Password:</label>
            <input type="password" name="password_confirmation" required>
            {% if error_message == 'Passwords do not match' %}
            <span class="error">Passwords do not match</span>
            {% endif %}
        </div>
        <div>
            <label>URL:</label>
            <input type="text" name="url" required>
            {% if error_message == 'Invalid URL' %}
            <span class="error">Invalid URL</span>
            {% endif %}
        </div>
        <button type="submit">Submit</button>
    </form>
</div>

<script>
    document.getElementById('toggleForm').addEventListener('click', () => {
        const form = document.getElementById('employeeForm');
        form.style.display = form.style.display === 'none' ? 'block' : 'none';
    });
</script>

{% if error_message %}
<p class="error">{{ error_message }}</p>
{% endif %}
{% endblock %}

IGI/LR5/LabRab5_IGI/onlineshop/templates/onlineshop/article_detail.html
{% extends "base_generic.html" %}

{% block content %}
    <h1 class="itim-regular">{{ article.title }}</h1>
    <div style="text-align: center;">
        <img src="{{ article.image.url }}" alt="{{ article.title }}" style="width: 100%; height: auto;">
    </div>
    <div class="article-content">
        <p>{{ article.content }}</p>
    </div>
{% endblock %}

IGI/LR5/LabRab5_IGI/onlineshop/templates/onlineshop/client_list_for_employee.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Client List</h1>

  <form method="GET" action="{% url 'clients' %}">
    <input type="text" name="search" placeholder="Search clients" value="{{ request.GET.search }}">
    <input type="submit" value="Search">
  </form>

  <table>
    <thead>
      <tr>
        <th>Username</th>
        <th>Email</th>
        <th>Date Joined</th>
      </tr>
    </thead>
    <tbody>
    {% for client in object_list %}
      <tr>
        <td>{{ client.user.username }}</td>
        <td>{{ client.user.email }}</td>
        <td>{{ client.user.date_joined }}</td>
      </tr>
    {% empty %}
      <tr>
        <td colspan="3">No clients found.</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>

{% endblock %}

IGI/LR5/LabRab5_IGI/onlineshop/templates/onlineshop/jobs.html
{% extends "base_generic.html" %}

{% block content %}
    <article itemscope itemtype="https://schema.org/JobPosting">
        <header>
            <h1 class="itim-regular" itemprop="title">Jobs</h1>
        </header>
        <section>
            {% for job in jobs %}
                <article itemscope itemtype="https://schema.org/JobPosting" class="job-posting">
                    <header>
                        <h2 itemprop="title" class="itim-regular">{{ job.title }}</h2>
                    </header>
                    <p itemprop="description">{{ job.description }}</p>
                </article>
                <div class="clear"></div>
            {% empty %}
                <p>There are no jobs</p>
            {% endfor %}
        </section>
    </article>
{% endblock %}

IGI/LR5/LabRab5_IGI/onlineshop/templates/onlineshop/manufacturer_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1 class="itim-regular">Name: {{ manufacturer.name }}</h1>

  <div class="manufacturer-details">
    {% if manufacturer.logo %}
      <img src="{{ manufacturer.logo.url }}" alt="{{ manufacturer.name }}" class="manufacturer-logo">
    {% endif %}
    <p><strong>Description:</strong> {{ manufacturer.description }}</p>
    <p><strong>Location:</strong> {{ manufacturer.address }}</p>
    <p><strong>Phone:</strong> {{ manufacturer.phone }}</p>
    <p><strong>Website:</strong> <a href="{{ manufacturer.website }}" target="_blank">{{ manufacturer.website }}</a></p>
  </div>

  <div class="products-section">
    <h4 class="itim-regular table-title">Products</h4>
    <table class="product-table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Price</th>
          <th>Description</th>
          <th>Id</th>
        </tr>
      </thead>
      <tbody>
        {% for product in manufacturer.product_set.all %}
        <tr>
          <td><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></td>
          <td>{{ product.price }}</td>
          <td>{{ product.description }}</td>
          <td class="text-muted">{{ product.id }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

IGI/LR5/LabRab5_IGI/onlineshop/templates/onlineshop/orders_by_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Order List</h1>

    {% if order_list %}
    <ul>
      {% for order in order_list %}
      <li>
       <a href="{% url 'order-detail' order.id %}">Order {{ order.order_date|date:"d.m.Y" }} - {{ order.get_status_display }}</a> (Total price: {{ order.total_price }})
      </li>
      {% endfor %}
    </ul>
    {% else %}
      <p>You have no orders.</p>
    {% endif %}
{% endblock %}

IGI/LR5/LabRab5_IGI/onlineshop/templates/onlineshop/pickup_location_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Pickup Locations</h1>
  <ul>
    {% for location in object_list %}
      <li>
        <h2>{{ location.name }}</h2>
        <p>Address: {{ location.address }}</p>
      </li>
    {% empty %}
      <li>No pickup locations available.</li>
    {% endfor %}
  </ul>
{% endblock %}

IGI/LR5/LabRab5_IGI/onlineshop/templates/onlineshop/product_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <div class="product-card">
    <img src="{{ product.image.url }}" alt="{{ product.name }}">
    <h1>Name: {{ product.name }}</h1>
    <p><strong>Description:</strong> {{ product.description }}</p>
    <p class="product-price"><strong>Price:</strong> {{ product.price }}</p>
    <p><strong>Product type:</strong> {{ product.product_type }}</p>
    <p><strong>Unit of measure:</strong> {{ product.unit_of_measure }}</p>
    <p><strong>Manufacturer:</strong> <a href="{% url 'manufacturer-detail' product.manufacturer.id %}">{{ product.manufacturer }}</a></p>
    {% if user.is_authenticated and user.client %}
    <form method="POST" action="{% url 'add_to_cart' product.id %}">
      {% csrf_token %}
      <input type="submit" value="Add to cart" class="btn-emerald">
    </form>
    {% endif %}
  </div>
{% endblock %}

IGI/LR5/LabRab5_IGI/onlineshop/templates/onlineshop/productinstance_list_all_orders.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>All Orders</h1>

    {% if order_list %}
    <ul>
      {% for order in order_list %}
      <li>
         <a href="{% url 'change-status-employee' order.id %}">Order {{ order.order_date|date:"d.m.Y" }} - {{ order.get_status_display }}</a> (Total price: {{ order.total_price }}, Ordered by: {{ order.client.user.username }})
      </li>
      {% endfor %}
    </ul>
    {% else %}
        <p>There are no orders.</p>
    {% endif %}
{% endblock %}