IGI/LR5/LabRab5_IGI/LabRab5_IGI/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path
from django.urls import include

from onlineshop.views import RegisterView

urlpatterns = [
    path('admin/', admin.site.urls),
]
urlpatterns += [
    path('onlineshop/', include('onlineshop.urls')),
]
from django.views.generic import RedirectView

urlpatterns += [
    path('', RedirectView.as_view(url='/onlineshop/', permanent=True)),
]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += [
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('accounts/', include('django.contrib.auth.urls')),
]
urlpatterns += [
    path('sign-up', RegisterView.as_view(), name='sign-up'),
]
from django.conf import settings
from django.conf.urls.static import static

# ... your existing urlpatterns ...

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

IGI/LR5/LabRab5_IGI/onlineshop/urls.py
from django.urls import path
from . import views
from django.urls import re_path

from .views import AllClientsForEmployeeView, LogoutView

# urlpatterns = [
#     path('', views.index, name='index'),
#     path('products/', views.ProductListView.as_view(), name='products'),
#
#
#     path('product/<int:pk>', views.ProductDetailView.as_view(), name='product-detail'),
# ]

urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^products/$', views.ProductListView.as_view(), name='products'),
    re_path(r'^product/(?P<pk>\d+)$', views.ProductDetailView.as_view(), name='product-detail'),
    re_path(r'^manufacturers/$', views.ManufacturerListView.as_view(), name='manufacturers'),
    re_path(r'^manufacturers/(?P<pk>\d+)$', views.ManufacturerDetailView.as_view(), name='manufacturer-detail'),
]
urlpatterns += [
    re_path(r'^myproducts/$', views.OrderedProductsByUserListView.as_view(), name='my-ordered'),
]
urlpatterns += [
    re_path(r'^all-orders/$', views.AllOrdersForEmployeeView.as_view(), name='all-orders'),
]
urlpatterns += [
    re_path(r'^order/(?P<pk>[-\w]+)/change-status/$', views.change_status_employee, name='change-status-employee'),

]
urlpatterns += [
    re_path(r'^orders/$', views.OrdersByUserListView.as_view(), name='my-orders'),
]
urlpatterns += [
    re_path(r'^orders/(?P<order_id>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/$', views.OrderedProductsByUserListView.as_view(), name='order-detail'),
]
urlpatterns += [
    # ... your other url patterns here ...

    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
]
urlpatterns += [
    re_path(r'^cart/$', views.CartView.as_view(), name='cart'),
]
urlpatterns += [
    path('create-order/', views.create_order, name='create-order'),
]

urlpatterns += [
    re_path(r'^increase-quantity/(?P<product_instance_id>[0-9a-f-]+)/$', views.increase_quantity,
            name='increase-quantity'),
    re_path(r'^decrease-quantity/(?P<product_instance_id>[0-9a-f-]+)/$', views.decrease_quantity,
            name='decrease-quantity'),
    re_path(r'^remove-from-cart/(?P<product_instance_id>[0-9a-f-]+)/$', views.remove_from_cart,
            name='remove-from-cart'),
]

urlpatterns += [
    path('onlineshop/cart/apply-promo-code/', views.apply_promo_code, name='apply-promo-code'),
]
urlpatterns += [
    path('promo-codes/', views.PromoCodeListView.as_view(), name='promo-codes'),
]
urlpatterns += [
    path('pickup-locations/', views.PickupLocationListView.as_view(), name='pickup-locations'),
]
urlpatterns += [
    path('clients/', views.client_list, name='clients'),
]

urlpatterns += [
    path('clients/all/', views.AllClientsForEmployeeView.as_view(), name='all-clients'),
]
from .views import EmployeeListView

urlpatterns += [
    path('contacts/', EmployeeListView.as_view(), name='contacts'),
]
from .views import ReviewListView, ReviewCreateView

urlpatterns += [
    path('reviews/', ReviewListView.as_view(), name='reviews'),
    path('reviews/add/', ReviewCreateView.as_view(), name='add-review'),
]
from .views import employee_stats

urlpatterns += [
    path('employee-stats/', employee_stats, name='employee-stats'),
]
urlpatterns += [
    path('logout/', LogoutView.as_view(), name='logout'),
]
urlpatterns += [
    path('privacy-policy/', views.privacy_policy, name='privacy_policy'),
]
urlpatterns += [
    path('news/', views.news, name='news'),
    path('news/<int:article_id>/', views.article_detail, name='article_detail'),
]
urlpatterns += [
    path('about/', views.about, name='about'),
]
urlpatterns += [
    path('faq/', views.faq, name='faq'),
]
urlpatterns += [
    path('jobs/', views.jobs, name='jobs'),
]
from django.urls import path
from . import views

urlpatterns += [
    path('employees/', views.employee_table, name='employee_table'),
]

urlpatterns += [
    path('add_employee/', views.add_employee, name='add_employee'),
    # Другие маршруты
]

IGI/LR5/LabRab5_IGI/onlineshop/models.py
import uuid

from django.db import models
from django.db.models.signals import m2m_changed
from django.dispatch import receiver
from django.urls import reverse

import sys
from django.contrib.auth.models import User, Group

sys.path.append('D:\\3 SEM\\253503_TIMOSHEVICH_25\\IGI\\LR5\\LabRab5_IGI\\.venv\\Lib\\site-packages')

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Employee(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, default=3)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    position = models.CharField(max_length=100)
    photo = models.ImageField(upload_to='', null=True, blank=True)
    job_description = models.TextField(default='')
    phone = models.CharField(max_length=20, default='')
    email = models.EmailField(default='default@email.com')

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        group = Group.objects.get(name='Employees')
        self.user.groups.add(group)


class Client(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, default=2)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    phone_number = models.CharField(max_length=20, default='', blank=True)

    def __str__(self):
        return f"{self.user.username}"

    class Meta:
        ordering = ["last_name", "first_name"]

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        group = Group.objects.get(name='Shop Members')
        self.user.groups.add(group)


class ProductType(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Manufacturer(models.Model):
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=200)
    phone = models.CharField(max_length=20)
    logo = models.ImageField(upload_to='images/', null=True)
    website = models.URLField(null=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('manufacturer-detail', args=[str(self.id)])


class UnitOfMeasure(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    product_type = models.ForeignKey(ProductType, on_delete=models.CASCADE)
    manufacturer = models.ForeignKey("Manufacturer", on_delete=models.CASCADE, null=True)
    unit_of_measure = models.ForeignKey(UnitOfMeasure, on_delete=models.SET_NULL, null=True)
    image = models.ImageField(upload_to='product_images/', blank=True, null=True)
    # image = models.ImageField(upload_to='products/', null=True, blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product-detail', args=[str(self.id)])


class ProductInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text="Unique ID for this particular product across whole shop")
    product = models.ForeignKey('Product', on_delete=models.SET_NULL, null=True)
    # order = models.ForeignKey(Order, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    customer = models.ForeignKey(Client, on_delete=models.SET_NULL, null=True, blank=True)

    @property
    def total_price(self):
        return self.product.price * self.quantity

    class Meta:
        permissions = (("can_mark_issued", "Set product as issued"),)

    def __str__(self):
        """
        String for representing the Model object
        """
        return '%s (%s)' % (self.id, self.product.name)


class PickupLocation(models.Model):
    name = models.CharField(max_length=200)
    address = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class PromoCode(models.Model):
    code = models.CharField(max_length=10)
    discount = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.code


class Order(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text="Unique ID for this particular product across whole shop")
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    products = models.ManyToManyField(ProductInstance)
    order_date = models.DateTimeField(auto_now_add=True)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)
    promo_code = models.ForeignKey(PromoCode, on_delete=models.SET_NULL, null=True, blank=True)  # new field
    pickup_location = models.ForeignKey(PickupLocation, on_delete=models.SET_NULL, null=True, blank=True)

    LOAN_STATUS = (
        ('p', 'Processing'),
        ('s', 'Shipped'),
        ('d', 'Delivered'),
        ('i', 'Issued'),
    )

    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='p',
                              help_text='Status of the order')

    def save(self, *args, **kwargs):
        self.total_price = sum(
            product_instance.product.price * product_instance.quantity for product_instance in self.products.all())
        if self.promo_code:
            self.total_price *= (1 - self.promo_code.discount / 100)
        super().save(*args, **kwargs)

    def update_total_price(self):
        total_price = sum(
            product_instance.product.price * product_instance.quantity for product_instance in self.products.all())
        if self.promo_code:
            total_price *= (1 - self.promo_code.discount / 100)
        self.total_price = total_price
        self.save()

    def __str__(self):
        return f"Order {self.id} by {self.client}"


@receiver(m2m_changed, sender=Order.products.through)
def update_total_price(sender, instance, action, **kwargs):
    if action == "post_add" or action == "post_remove":
        instance.total_price = sum(
            product_instance.product.price * product_instance.quantity for product_instance in instance.products.all())
        instance.save()


class Cart(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    products = models.ManyToManyField(ProductInstance)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)
    promo_code = models.ForeignKey(PromoCode, on_delete=models.SET_NULL, null=True, blank=True)  # new field

    def __str__(self):
        return f"Cart for {self.client}"

    def update_total_price(self):
        total_price = sum(
            product_instance.product.price * product_instance.quantity for product_instance in self.products.all())
        if self.promo_code:
            total_price *= (1 - self.promo_code.discount / 100)
        self.total_price = total_price
        self.save()


class Review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rating = models.IntegerField()
    text = models.TextField()
    date = models.DateTimeField(auto_now_add=True)


from django.utils import timezone


class Article(models.Model):
    title = models.CharField(max_length=200)
    summary = models.CharField(max_length=200)
    image = models.ImageField(upload_to='articles/')
    content = models.TextField()
    date_added = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title


class CompanyInfo(models.Model):
    text = models.TextField()
    video = models.FileField(upload_to='company_info/')
    logo = models.ImageField(upload_to='company_info/')
    banner1 = models.ImageField(upload_to='company_info/', null=True, blank=True)
    banner2 = models.ImageField(upload_to='company_info/', null=True, blank=True)
    banner3 = models.ImageField(upload_to='company_info/', null=True, blank=True)  # Новое поле
    privacy_policy = models.FileField(upload_to='employee_photos/policies/', null=True, blank=True)

    audio = models.FileField(upload_to='company_info/', null=True, blank=True)

    history = models.TextField()
    details = models.TextField()

    def __str__(self):
        return "Company Information"


class FAQ(models.Model):
    question = models.TextField()
    answer = models.TextField()
    date_added = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.question


class Job(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()

    def __str__(self):
        return self.title

IGI/LR5/LabRab5_IGI/onlineshop/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
import datetime  # for checking renewal date range.

from .models import Order, PickupLocation


class OrderStatusForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['status']


from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from datetime import date, timedelta
from django.core.validators import RegexValidator


class RegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)
    date_of_birth = forms.DateField(
        help_text="Required. Format: DD.MM.YYYY",
        input_formats=['%d.%m.%Y']
    )
    phone_number = forms.CharField(
        validators=[
            RegexValidator(
                regex=r'^\+375 \((29|33|44|25)\) \d{3}-\d{2}-\d{2}$',
                message="Phone number must be entered in the format: '+375 (29) XXX-XX-XX'. Up to 15 digits allowed."
            )
        ]
    )

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ["username", "email", "password1", "password2", "date_of_birth", "phone_number"]

    def clean_date_of_birth(self):
        dob = self.cleaned_data.get('date_of_birth')
        today = date.today()
        if (dob.year + 18, dob.month, dob.day) > (today.year, today.month, today.day):
            raise forms.ValidationError('You must be at least 18 years old to register.')
        return dob


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['pickup_location']
        widgets = {
            'pickup_location': forms.Select(attrs={'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        self.fields['pickup_location'].empty_label = None


from django import forms
from .models import Review


class ReviewForm(forms.ModelForm):
    RATING_CHOICES = [(i, str(i)) for i in range(1, 6)]

    rating = forms.ChoiceField(choices=RATING_CHOICES, widget=forms.Select(), required=True, initial=5)

    class Meta:
        model = Review
        fields = ['rating', 'text']

IGI/LR5/LabRab5_IGI/onlineshop/templates/base_generic.html
<!doctype html>
<html lang="en">
<head>
  {% load static %}
  {% block title %}<title>Online Shop</title>{% endblock %}
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="author" content="Karina Timoshevich" />
  <meta name="description" content="Welcome to Online Shop, your go-to destination for high-quality food products. Discover our wide range of fresh and organic items, and enjoy our excellent customer service and fast delivery." />
  <link rel="icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">
  <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Itim&display=swap" rel="stylesheet">
</head>

  <body>
    <div class="container">
      <div class="sidebar">
        {% block sidebar %}
          <ul class="sidebar-nav itim-regular" >
            <li><a href="{% url 'index' %}">Home</a></li>
            <li><a href="{% url 'products' %}">All products</a></li>
            <li><a href="{% url 'manufacturers' %}">All manufacturers</a></li>
            <li><a href="{% url 'promo-codes' %}">Promocodes</a></li>
            <li><a href="{% url 'contacts' %}">Our employees</a></li>
            <li><a href="{% url 'reviews' %}">Reviews</a></li>
            <li><a href="{% url 'privacy_policy' %}">Privacy policy</a></li>
            <li><a href="{% url 'news' %}">News</a></li>
            <li><a href="{% url 'about' %}">About company</a></li>
            <li><a href="{% url 'faq' %}">FAQ</a></li>
            <li><a href="{% url 'jobs' %}">Job</a></li>

             {% if user.is_authenticated %}
                 <li>User: {{ user.get_username }}</li>
                 {% for group in user.groups.all %}
                    {% if group.name == "Shop Members" %}
                        <li><a href="{% url 'my-orders' %}">My Orders</a></li>
                        <li><a href="{% url 'cart' %}">My Cart</a></li>
                        <li><a href="{% url 'pickup-locations' %}">Pick-up points</a></li>
                    {% endif %}
                {% endfor %}

                {% if user.is_superuser %}
                    <li><a href="{% url 'all-orders' %}">All Orders</a></li>
                    <li><a href="{% url 'clients' %}">All clients</a></li>
                    <li><a href="{% url 'employee-stats' %}">All statistics</a></li>
                    <li><a href="{% url 'employee_table' %}">Employee</a></li>
                    {% if perms.onlineshop.can_mark_returned %}
                        {% if order and order.id %}
                            <li><a href="{% url 'change-status-employee' order.id %}">Change Order Status</a></li>
                        {% endif %}
                    {% endif %}
                {% else %}
                    {% for group in user.groups.all %}
                        {% if group.name == "Employees" %}
                            <li><a href="{% url 'all-orders' %}">All Orders</a></li>
                            <li><a href="{% url 'clients' %}">All clients</a></li>
                            <li><a href="{% url 'employee-stats' %}">All statistics</a></li>
                            {% if perms.onlineshop.can_mark_returned %}
                                {% if order and order.id %}
                                    <li><a href="{% url 'change-status-employee' order.id %}">Change Order Status</a></li>
                                {% endif %}
                            {% endif %}
                        {% endif %}
                    {% endfor %}
                {% endif %}
<form action="{% url 'logout' %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="next" value="{% url 'logout' %}">
    <button type="submit" class="btn btn-emerald">Logout</button>
</form>
    </li>
             {% else %}
                 <li><a href="{% url 'login'%}?next={% url 'index' %}">Login</a></li>
             {% endif %}
          </ul>
        {% endblock %}
      </div>
      <div class="content">{% block content %}{% endblock %}
      {% block pagination %}
{#  {% if is_paginated %}#}
{#    <div class="pagination">#}
{#      <span class="page-links">#}
{#        {% if page_obj.has_previous %}#}
{#          <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>#}
{#        {% endif %}#}
{#        <span class="page-current">#}
{#          Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.#}
{#        </span>#}
{#        {% if page_obj.has_next %}#}
{#          <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>#}
{#        {% endif %}#}
{#      </span>#}
{#    </div>#}
{#  {% endif %}#}
{% endblock %}
      </div>
    </div>
  </body>
</html>

IGI/LR5/LabRab5_IGI/onlineshop/templates/index.html
{% extends "base_generic.html" %}
{% block content %}

    <h1 class="itim-regular">Welcome to our shop!</h1>
{% load static %}

<div id="animation-area">
    <img src="{% static 'images/zelen.png' %}" class="product" id="product-1" />
    <img src="{% static 'images/eggs.png' %}" class="product" id="product-2" />
    <img src="{% static 'images/cheese.png' %}" class="product" id="product-3" />
    <img src="{% static 'images/cart.png' %}" class="cart" />
    <img src="{% static 'images/cloud.png' %}" class="cloud" />
    <img src="{% static 'images/milk.png' %}" class="product" id="product-1-2" />
    <img src="{% static 'images/flour.png' %}" class="product" id="product-2-3" />
    <img src="{% static 'images/house-clipart-hd-14.png' %}" id="house" />
    <img src="{% static 'images/tree.png' %}" class="tree" id="tree" />
    <div id="company-name">Online Store</div>
</div>

    <figure id="company-logo">
        <img src="{{ info.logo.url }}" alt="Company Logo">
        <figcaption>Company Logo</figcaption>
    </figure>

    <p>Current time: {{ current_date_formatted }}</p>
    <p>Current data: {{ calendar_text }}</p>
    <p id="countdown-timer">Loading countdown...</p>

    <h2 class="itim-regular">Partner Companies</h2>
    <div class="partner-blocks">
        {% for manufacturer in manufacturer_list %}
        <div class="itim-regular">
            <div class="partner-block">
                {% if manufacturer.logo %}
                    <img src="{{ manufacturer.logo.url }}" alt="{{ manufacturer.name }}" class="partner-logo">
                {% endif %}
            </div>
            <p class="partner-name">{{ manufacturer.name }}</p>
        </div>
        {% endfor %}
    </div>

<div class="slider-container">
    <div class="slides">
        <div class="slide">
            <a href="https://github.com/karina-timoshevich/IGI_new_name/tree/STRWEB_LR3/IGI/LR5/LabRab5_IGI">
            <img src="{{ info.banner1.url }}" alt="Banner 1" class="banner-image">
                  </a>
            <div class="slide-caption" id="caption-1">Fresh and healthy products straight from the farm to your table!</div>
        </div>
        <div class="slide">
              <a href="https://github.com/karina-timoshevich/IGI_new_name/tree/STRWEB_LR3/IGI/LR5/LabRab5_IGI">
            <img src="{{ info.banner2.url }}" alt="Banner 2" class="banner-image">
                    </a>
            <div class="slide-caption" id="caption-2">Daily essentials for your family — always fresh and available!</div>
        </div>
        <div class="slide">
              <a href="https://github.com/karina-timoshevich/IGI_new_name/tree/STRWEB_LR3/IGI/LR5/LabRab5_IGI">
            <img src="{{ info.banner3.url }}" alt="Banner 3" class="banner-image">
                    </a>
            <div class="slide-caption" id="caption-3">All your favorite ingredients in one place — for every recipe!</div>
        </div>
    </div>

    <div class="slider-controls">
    <button id="prev" aria-label="Previous Slide">&#9664;</button>
    <button id="next" aria-label="Next Slide">&#9654;</button>
    </div>

    <div class="pagination-sl" id="pagination">
        <span class="page" data-slide="0"></span>
        <span class="page" data-slide="1"></span>
        <span class="page" data-slide="2"></span>
    </div>

    <div id="slide-number">1/3</div>
</div>


    <h2 class="itim-regular">Latest Article</h2>


<div class="latest-article">
    <h3><a href="{% url 'article_detail' latest_article.id %}">{{ latest_article.title }}</a></h3>
    <p>{{ latest_article.summary }}</p>
</div>

    <label for="settings-toggle">Enable custom settings</label>
<input type="checkbox" id="settings-toggle" />
<div id="settings-container"></div>

<script>
    const user = { is_superuser: true };
    const settingsContainer = document.getElementById('settings-container');
    const settingsPanel = document.createElement('div');
    settingsPanel.id = 'settings-panel';

    const fontSizeDiv = document.createElement('div');
    fontSizeDiv.innerHTML = `
        <label for="font-size">Font size:</label>
        <select id="font-size">
            <option value="14px">14px</option>
            <option value="16px">16px</option>
            <option value="18px">18px</option>
            <option value="20px">20px</option>
        </select>
    `;
    settingsPanel.appendChild(fontSizeDiv);

    const textColorDiv = document.createElement('div');
    textColorDiv.innerHTML = `
        <label for="text-color">Text color:</label>
        <input type="color" id="text-color" value="#000000">
    `;
    settingsPanel.appendChild(textColorDiv);
document.getElementById('settings-toggle').addEventListener('change', function() {
    if (this.checked) {
        settingsPanel.style.display = 'block';
    } else {
        settingsPanel.style.display = 'none';
    }
});

    const bgColorDiv = document.createElement('div');
    bgColorDiv.innerHTML = `
        <label for="background-color">Background color:</label>
        <input type="color" id="background-color" value="#ffffff">
    `;
    settingsPanel.appendChild(bgColorDiv);
    if (user.is_superuser) {
        const slideDelayDiv = document.createElement('div');
        slideDelayDiv.innerHTML = `
            <label for="slide-delay">Slide delay (seconds):</label>
            <input type="number" id="slide-delay" value="5" min="1" step="1">
        `;
        settingsPanel.appendChild(slideDelayDiv);
    }

    settingsContainer.appendChild(settingsPanel);
</script>


{% block scripts %}
    <script src="{% static 'js/slider.js' %}"></script>
     <script src="{% static 'js/countdown.js' %}"></script>
    <script src="{% static 'js/settings.js' %}"></script>
{% endblock %}
{% endblock %}